services:
  rabbitmq:
    image: masstransit/rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y

  consumer:
    build:
      context: .
      dockerfile: ./Example.MassTransit.Consumer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672/
      - ConnectionStrings__Seq=http://seq:5341

  producer:
    build:
      context: .
      dockerfile: ./Example.MassTransit.Producer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672/
      - ConnectionStrings__Seq=http://seq:5341
